name: Liquibase Version & Status

on:
  workflow_dispatch:

jobs:
  liquibase-local:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Liquibase Version
        run: |
          echo "=== LIQUIBASE VERSION ==="
          C:\liquibase\liquibase.bat --version

      - name: Show Liquibase Status
        run: |
          echo "=== LIQUIBASE STATUS ==="
          C:\liquibase\liquibase.bat --defaultsFile="C:\proyectos\liquibase-demo\liquibase.properties" --classpath="C:\proyectos\liquibase-demo\drivers\postgresql-42.7.4.jar" status --verbose
